[cp]
cp ansible_host=44.213.81.156 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/test_key.pem

[workers]
w-1 ansible_host=18.206.81.64 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/test_key.pem
w-2 ansible_host=44.200.31.57 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/test_key.pem

[kube_nodes:children]
cp
workers